name: Run Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Make + build dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Install project
        run: make install

      - name: Run tests
        run: make test
