name: Check (Lint + Test)

on:
  push:
    branches: ["main", "dev", "feature/**"]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: sudo apt-get update && sudo apt-get install -y make
      - run: make ci
