name: Check (Lint + Test)

on:
  push:
    branches: ["main", "dev", "feature/**"]
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml

  test:
    uses: ./.github/workflows/_test.yml
    needs: lint
