name: Check (Lint + Test)

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Make and Python build tools
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run checks
        run: make ci-release
